# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\YandexDisk\Work\ProjectsRepositories\20230821_RousettusDataProcessing\RousettusDataProcessing\GUI\UI\DataProcessing\AddEnWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEnWindowDialog(object):
    def setupUi(self, AddEnWindowDialog):
        AddEnWindowDialog.setObjectName("AddEnWindowDialog")
        AddEnWindowDialog.resize(251, 151)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEnWindowDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddEnWindowDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.win_name_line = QtWidgets.QLineEdit(AddEnWindowDialog)
        self.win_name_line.setObjectName("win_name_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.win_name_line)
        self.label_2 = QtWidgets.QLabel(AddEnWindowDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.subwin_name_line = QtWidgets.QLineEdit(AddEnWindowDialog)
        self.subwin_name_line.setObjectName("subwin_name_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subwin_name_line)
        self.label_5 = QtWidgets.QLabel(AddEnWindowDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lhb_spinbox = QtWidgets.QDoubleSpinBox(AddEnWindowDialog)
        self.lhb_spinbox.setMaximum(99999.0)
        self.lhb_spinbox.setObjectName("lhb_spinbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lhb_spinbox)
        self.label_6 = QtWidgets.QLabel(AddEnWindowDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rhb_spinbox = QtWidgets.QDoubleSpinBox(AddEnWindowDialog)
        self.rhb_spinbox.setPrefix("")
        self.rhb_spinbox.setMaximum(99999.0)
        self.rhb_spinbox.setObjectName("rhb_spinbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rhb_spinbox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(AddEnWindowDialog)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.cancel_button = QtWidgets.QPushButton(AddEnWindowDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddEnWindowDialog)
        QtCore.QMetaObject.connectSlotsByName(AddEnWindowDialog)

    def retranslateUi(self, AddEnWindowDialog):
        _translate = QtCore.QCoreApplication.translate
        AddEnWindowDialog.setWindowTitle(_translate("AddEnWindowDialog", "Dialog"))
        self.label.setText(_translate("AddEnWindowDialog", "Window name"))
        self.label_2.setText(_translate("AddEnWindowDialog", "Subwindow name"))
        self.label_5.setText(_translate("AddEnWindowDialog", "Left hand subwindow border"))
        self.lhb_spinbox.setSuffix(_translate("AddEnWindowDialog", "KEv"))
        self.label_6.setText(_translate("AddEnWindowDialog", "Right hand subwindow border"))
        self.rhb_spinbox.setSuffix(_translate("AddEnWindowDialog", "KEv"))
        self.add_button.setText(_translate("AddEnWindowDialog", "Add"))
        self.cancel_button.setText(_translate("AddEnWindowDialog", "Cancel"))
