# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\YandexDisk\Work\ProjectsRepositories\20230821_RousettusDataProcessing\RousettusDataProcessing\GUI\UI\DataProcessing\GNSS_import_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Import_GNSS_widget(object):
    def setupUi(self, Import_GNSS_widget):
        Import_GNSS_widget.setObjectName("Import_GNSS_widget")
        Import_GNSS_widget.resize(727, 589)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Import_GNSS_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Import_GNSS_widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ds_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ds_label.sizePolicy().hasHeightForWidth())
        self.ds_label.setSizePolicy(sizePolicy)
        self.ds_label.setMinimumSize(QtCore.QSize(100, 20))
        self.ds_label.setObjectName("ds_label")
        self.horizontalLayout.addWidget(self.ds_label)
        self.ds_combobox = QtWidgets.QComboBox(self.groupBox)
        self.ds_combobox.setMinimumSize(QtCore.QSize(120, 20))
        self.ds_combobox.setObjectName("ds_combobox")
        self.horizontalLayout.addWidget(self.ds_combobox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.main_import_widget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_import_widget.sizePolicy().hasHeightForWidth())
        self.main_import_widget.setSizePolicy(sizePolicy)
        self.main_import_widget.setObjectName("main_import_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_import_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.main_import_widget)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Import_GNSS_widget)
        QtCore.QMetaObject.connectSlotsByName(Import_GNSS_widget)

    def retranslateUi(self, Import_GNSS_widget):
        _translate = QtCore.QCoreApplication.translate
        Import_GNSS_widget.setWindowTitle(_translate("Import_GNSS_widget", "Import GNSS Data"))
        self.groupBox.setTitle(_translate("Import_GNSS_widget", "Data source"))
        self.ds_label.setText(_translate("Import_GNSS_widget", "Data source type"))
